[mediaTypes]
  [mediaTypes."text/redirects"]
    suffixes = [""]

[outputFormats]
  [outputFormats.Redirects]
  	name = "redirects"
    baseName = ""
    isPlainText = true
    mediaType = "text/redirects"
    permalinkable = false